import vgamepad as vg

XINPUT_BUTTON_MAP = {
    "A": vg.XUSB_BUTTON.XUSB_GAMEPAD_A,
    "B": vg.XUSB_BUTTON.XUSB_GAMEPAD_B,
    "X": vg.XUSB_BUTTON.XUSB_GAMEPAD_X,
    "Y": vg.XUSB_BUTTON.XUSB_GAMEPAD_Y,
    "UP": vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_UP,
    "DOWN": vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN,
    "LEFT": vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT,
    "RIGHT": vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_RIGHT,
    "START": vg.XUSB_BUTTON.XUSB_GAMEPAD_START,
    "SELECT": vg.XUSB_BUTTON.XUSB_GAMEPAD_BACK,
    "LB": vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER,
    "RB": vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_SHOULDER,
    "RSB": vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_THUMB,
    "LSB": vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_THUMB,
}

DS4_BUTTON_MAP = {
    "A": vg.DS4_BUTTONS.DS4_BUTTON_CROSS,
    "B": vg.DS4_BUTTONS.DS4_BUTTON_CIRCLE,
    "X": vg.DS4_BUTTONS.DS4_BUTTON_SQUARE,
    "Y": vg.DS4_BUTTONS.DS4_BUTTON_TRIANGLE,
    "START": vg.DS4_BUTTONS.DS4_BUTTON_OPTIONS,
    "SELECT": vg.DS4_BUTTONS.DS4_BUTTON_SHARE,
    "LB": vg.DS4_BUTTONS.DS4_BUTTON_SHOULDER_LEFT,
    "RB": vg.DS4_BUTTONS.DS4_BUTTON_SHOULDER_RIGHT,
    "LT": vg.DS4_BUTTONS.DS4_BUTTON_TRIGGER_LEFT,
    "RT": vg.DS4_BUTTONS.DS4_BUTTON_TRIGGER_RIGHT,
    "LSB": vg.DS4_BUTTONS.DS4_BUTTON_THUMB_LEFT,
    "RSB": vg.DS4_BUTTONS.DS4_BUTTON_THUMB_RIGHT,
    "DOWN": vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_SOUTH,
    "UP": vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_NORTH,
    "LEFT": vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_WEST,
    "RIGHT": vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_EAST,
}